### ISSUE TITLE
Renaming reducers

### ISSUE THREAD

**Issue by siawyoung** [siawyoung/remerge#1]
E.g. `addArrayReducer` and `deleteArrayReducer` is a bit of a misnomer - it can sound like you're adding an array, instead of adding **to** an array.

Maybe `arrayAddReducer` and `arrayDeleteReducer`? Ditto for object reducers. 

@matthewcheok

**Comment by matthewcheok** [comment]
Related discussion but `deleteId` feels rather vague and there's nothing explicitly an `id`. I'd suggest changing to `deleteIndex` in the array reducer and `deleteKey` in the object reducer.

**Comment by siawyoung** [comment]
Closed with #3
