### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by matthewcheok** [siawyoung/remerge#33]
We could use some sort of memoization to map an action type to it right position in the state tree. Maybe the recursion is expensive - we're basically performing a BFS on every action!

Also, once we found an action, might be a good idea to consider some form of early termination.

EDIT: On further thought, we could, in the preprocessing step, generate a map of all possible action types to the right reducer.

**Comment by siawyoung** [comment]
Yes, generating a map of all possible action types was what I was thinking of too.

**Comment by matthewcheok** [comment]
Fixed in #34
